### ISSUE TITLE
package.json format for scripts and binaries

### ISSUE THREAD

**Issue by juanibiapina** [bpkg/bpkg#17]
It seems to me you based your package.json on the npm format: https://www.npmjs.org/doc/package.json.html

But by reading the documentation, the 'scripts' member is used for lifecycle management, not binaries. The 'bin' member is for listing executables that should go to the path.

Did you depart from this format on purpose?

Examples:
https://github.com/sstephenson/bats/blob/master/package.json#L7
https://github.com/progrium/gh-release/blob/master/package.json#L7

I'm planning to add this feature to [basher](https://github.com/juanibiapina/basher), and it would be really sad if basher and bpkg were incompatible.

**Comment by fidian** [comment]
It's been a sad year with no updates.  Is there any movement on this issue that I have not seen?  It looks like people are behind a new format and are just deciding what the new format would look like.  I would love to see `package.json` renamed so people don't automatically think the repository is for node.

I'm in favor of the sanitized config files as linked earlier.  Also there was talk about INI files.  I have an INI file parser in [mr-fusion](https://github.com/tests-always-included/mr-fusion/blob/master/mr-fusion).  It still uses eval, but the values are sanitizes.  Look at parse-ini, ini-var and encode-string and I'd welcome any critiques to improve the library.

I'm debating splitting up my existing bash code into reusable libraries and I think it would be wonderful to combine forces.  I'm a fan of bpkg because I have to install just a single file and there's the online repository.  I like basher because it is tested.

**Comment by jwerle** [comment]
@fidian any suggestions on a new format? This would of course invalidate every package out there using `package.json`.

`package.json` isn't just owned by npm. It is used by other package management systems like clib and duo.

cc @stephenmathieson @ccarpita

**Comment by stephenmathieson** [comment]
i stand by https://github.com/bpkg/bpkg/issues/17#issuecomment-48046444 still :)

**Comment by jwerle** [comment]
@stephenmathieson +1 :]

**Comment by fidian** [comment]
@stephenmathieson I am only talking about things I suffered through, not specifically the format of the file.  Please consider scripts that set up repositories in a generic way.  Here's a simplified example:

    git clone http://github.com/whatever/whereever.git
    (
        cd wherever
        git submodule update --init --recursive
        [[ -f composer.json ]] && composer install
        [[ -f bower.json]] && bower install
        [[ -f Makefile ]] && make
        [[ -f Gruntfile ]] && grunt
        [[ -f requirements.txt ]] && pip install -f requirements.txt
        [[ -f package.json ]] && npm install
        # How do we detect that bpkg is supposed to run instead or in addition to npm?
    )
    echo "Project checked out and dependencies installed"

With the popularity of node and npm, I would see people googling for `package.json` and hitting node instead of this package.  Those unfortunate souls would be confused.  Also, we now can't have both node modules and bpkg modules in the same project because the `package.json` files conflict with each other.

I'd advocate simply using `bpkg.json` and falling back to `package.json` when `bpkg.json` does not exit.  Later on this format can be changed to be an INI file or a shell script or whatnot.

If appropriate, I can make a separate issue or a pull request and essentially split this issue into two (one for rename, a second for the format).  I strongly support a new format and eliminating JSON, but that can come as a later step.  For now I just want to have both npm and bpkg coexist.

**Comment by ccarpita** [comment]
I've personally found `package.json` to be a point of confusion, and would prefer to see something along the lines of `bpkg.json` as bpkg "owns" the formatting.  Maybe a crazy idea, but if we also required a dependency on [jq](https://stedolan.github.io/jq/) then using json as a standard configuration format wouldn't be so bad.

**Comment by isaacs** [comment]
So... I get that bpkg is for bash, and npm is for JavaScript.

Funny story.  I have [this bash program](https://github.com/isaacs/nave), which I'm currently putting in npm already (since it's primarily used by Node users), and I'd love to *also* put it in bpkg, since this is a bash thing.

Also, since bash programs are frequently going to be CLI utilities, and npm is frequently used for the same, it's not so weird an idea that things might exist in both places.  (See also overlap between npm and rubygems with system package managers like apt-get and yum.)  There's already a bpkg package that installs Node, not so strange that someone might use that to have a node-and-bash hybrid type thing.  Quite a lot of Node users use bash pretty regularly, after all.

I think using a well-established filename convention like `package.json`, while making needlessly incompatible choices in how this file is interpreted, is not the best approach.  Especially when there's already a well-established way to express exactly what bpkg's `scripts` field is being used for, and literally infinite ways to express this that *don't* conflict with the many years-long legacy of extant npm packages.

I'd suggest inventing a new json filename which isn't already in use, or using package.json in ways that don't conflict.

**Comment by jwerle** [comment]
@isaacs I agree. `package.json` was a poor choice now that several bpkg packages exist this creates confusion for people trying to differentiate bpkg from npm. Any suggestions for a new filename?

**Comment by isaacs** [comment]
I'd suggest a two-fold approach:

1. If `bpkg.json` is present, use that.
2. Else, if `package.json` is present, use that, but handle scripts/bin/etc. using npm's semantics.

Using npm's json semantics is probably a good idea for (1) anyway, if possible, because you take advantage of a lot of documentation and expectations, without having to explain (or invent!) the rationale for the differences.

Like the example with nave, people are already using npm for some bash packages.  May as well use what works :)

**Comment by jwerle** [comment]
@isaacs I like this approach. It ensures backwards compatibility with existing bpkg packages that are using the `package.json` file at the very least. I'l try to have a patch up soon if everyone agrees. cc @bpkg/owners @stephenmathieson @juanibiapina

**Comment by brock** [comment]
:+1: for `bpkg.json`

**Comment by juanibiapina** [comment]
Cool!

**Comment by jasonkarns** [comment]
Just dropping in to point out that this is coming to a head soon.

https://github.com/ztombol/bats-core
and https://github.com/ztombol/bats-assert

We (nodenv org) will likely soon be using bats-core and bats-assert for our bats test assertions. nodenv is a bash utility, but for managing node versions. being a bash program, our test suite is in bats. However, we use npm for *managing* nodenv (and its associated plugin repos). (for versioning, releases, tagging, scripting, dependencies etc)

I can't speak for @ztombol, but bats-core and bats-assert may very well have an npm-compatible package.json. Personally, I think `package.json` works great as a manifest, since the majority of npm's manifest needs are shared with bpkg. It would only require that bpkg leverage npm's semantics for the package.json fields. I think this is already possible, given the current functionality. (just leveraging `bin` and `files` instead of `scripts` and leveraging `scripts` as hook scripts or run-scripts)

I don't see a reason to duplicate package.json's metadata into a bpkg.json file, especially if the semantics are identical, only with different keynames. This would be a pain to keep in sync, for any libs that need both. (see also, annoyance and pain in dealing with duplicate manifests between component.json, bower.json and package.json, when most/all the data therein was identical)

**Comment by isaacs** [comment]
I agree with @jasonkarns.  Essentially the same use-case as nave, which I mentioned initially: https://github.com/bpkg/bpkg/issues/17#issuecomment-177363443

There is quite a lot of overlap between bash and node programmers, and bash and node programs.  Node is a command line utility, and used for writing command line utilities, and bash is the unix command line.  Any divergence from established patterns should be done only when there is a very significant benefit to be had, because that divergence is very costly.  I don't see the benefit in this case.

**Comment by jwerle** [comment]
@isaacs @jasonkarns Okay, I think with about a year and a half of discussion on this subject, we should move towards implementing the [package.json](https://docs.npmjs.com/files/package.json) specification as much as possible. Global command utilities should be defined with `.bin` and `.scripts => `.files` is an obvious change.

**Comment by ztombol** [comment]
Hi! Developer of `bats-core` and `bats-assert` here. I'm not familiar with `bpkg`, `basher` or `npm`, but I would love to merge support for them. @juanibiapina has already started working on [`basher` support](https://github.com/ztombol/bats-docs/issues/1), and @jasonkarns on [`npm` support](https://github.com/ztombol/bats-core/pull/2).

If these package managers could share a common manifest specification that would make everyone's life easier. Developers could easily support 3 different package managers, and users would have a wider selection of packages available for their favourite manager.

Like I've said, I'm not familiar with the intricacies of using a shared pacakge manifest (from this discussion it seems possible), but it seems that everybody would benefit.

**Comment by fidian** [comment]
I have a concern that npm-specific properties do not overlap with bpkg-specific properties.  For instance, npm uses "dependencies" like so:

```
{
    "dependencies": {
        "some-npm-module": "version"
    }
}
```

I would not want bpkg to reuse "dependencies" in their spec.  Doing so would pollute the npm's list of dependencies and "npm install" would fail.  Instead, the bpkg-specific dependencies should use their own property.

Here's a bad example so you can see what I mean.  With this, now neither tool can fully complete their task of installing dependencies.

```
{
    "dependencies": {
        "some-npm-module": "version",
        "some-bpkg-dependency": "version"
    }
}
```

Further, one should not conflict with any other tool that has a tolerably significant market share that may overlap with bpkg.  [npm](https://docs.npmjs.com/files/package.json) is one such tool, but there are also [Mozilla add-ons](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json) and [jspm's extensions](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm) to the package.json spec.

I see two options.  You can define your own filename and stick to it, thus you own the spec.  Alternately you can try to settle in nicely with package.json by carefully examining what others are doing to extend that file in their own way and try to ensure you don't conflict.

**Comment by juanibiapina** [comment]
Just to reiterate my opinion, since it has been a while:

I think having two package managers for different languages use the same file name is not a good idea. Imagine the problems we could have if rubygems also used package.json. It would be very difficult to know which entries are used by which tool and how.

Basher and bpkg, on the other hand, could easily share a package format. But if they don't, it shouldn't be a major concern anyway, since they tackle the problem in very different ways.

Since it has been a while, I've already adopted `package.sh` for basher, and I think it has worked well. If you decide to use bpkg.json, basher could easily use it as a fallback.

**Comment by ccarpita** [comment]
If possible, I would retain as many semantics as possible from npm conventions, and still use a distinct file named `bpkg.json`, as it explicitly indicates support for bpkg implementations while avoiding the need for per-field conflict resolution.  It just seems like unnecessary surface area for issues in the future to attempt to maintain partial compatibility with the evolving npm standards.

**Comment by jasonkarns** [comment]
I have also reversed my opinion and now agree with what @juanibiapina and @ccarpita are saying above. New file (perhaps new format, whatever works for bpkg and basher), but hopefully using the same keywords and names with npm's semantics (simply to leverage well established naming conventions).

**Comment by Potherca** [comment]
As (ab)using `package.json` is already causing problems.

The most vocal contributors in this thread all seem to agree (also) having a `bpkg.json` is a good idea. 

So, moving forward, support for a `bpkg.json` needs to be added.

Both @fidian and @isaacs suggest an approach I wholeheartedly support:

> I'd advocate simply using `bpkg.json` and falling back to `package.json` when `bpkg.json` does not exit. Later on this format can be changed to be an INI file or a shell script or whatnot.

And

> I'd suggest a two-fold approach:
> 
> 1. If `bpkg.json` is present, use that.
> 2. Else, if `package.json` is present, use that, but handle scripts/bin/etc. using npm's semantics.

So:

- if a project has only a `package.json`, that is used
- if a project has only a `clib.json`, that is used
- if a project has both a `package.json` _and_ a `clib.json`, the  `clib.json` is used

Rather than recycling this issue, I'd suggest closing this issue with the common consensus as the conclusion and create a new issue specifically for adding `bpkg.json` support.

**Comment by jwerle** [comment]
@potherca I would love to see a PR for this 😉

**Comment by jwerle** [comment]
we've successfully done this for clibs by preferring `clib.json` and falling back to `package.json` if it exists! Would love to see it here as well

**Comment by Potherca** [comment]
I'm hoping to give BPKG some love soon, but I can't give any guarantees _yet_. 🤞

**Comment by SidIcarus** [comment]
@Potherca I'm going to take a gander at adding support for `bpkg.json`

@jwerle Would you be to link me, or point me in the right direction, to where this was done for `clibs`. Although I think I know what the logic would look like, having a reference wouldn't hurt. :)

**Comment by jwerle** [comment]
@SidIcarus take a look over here https://github.com/clibs/clib/blob/next/src/clib-install.c and here https://github.com/clibs/clib-package/tree/next

**Comment by jwerle** [comment]
we've finally done it - we moved to `bpkg.json`
